# Generated by Django 4.0.5 on 2022-06-10 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_transaction_extra_data_transaction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='sellers.seller'),
        ),
    ]
